<a href="https://colab.research.google.com/github/SADDLOVE/lab/blob/main/lab3/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Задание по практике 3

##Обработка пропущенных значений

Обработайте пропущенные значения:


* Удалите пропущенные значения
* Заполните при помощи медианы, среднего для числовых значений
* Заполните при помощи моды для категориальных значений
* Интерполируйте
Выведите статистку после каждого метода и объясните

In [ ]:
!pip install scikit-learn

In [19]:
import pandas as pd
import numpy as np

df = pd.read_csv('crimes_against_women_2001-2014.csv')
df

,Unnamed: 0,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
0,0,ANDHRA PRADESH,ADILABAD,2001,50,30,16,149,34,175,0
1,1,ANDHRA PRADESH,ANANTAPUR,2001,23,30,7,118,24,154,0
2,2,ANDHRA PRADESH,CHITTOOR,2001,27,34,14,112,83,186,0
3,3,ANDHRA PRADESH,CUDDAPAH,2001,20,20,17,126,38,57,0
4,4,ANDHRA PRADESH,EAST GODAVARI,2001,23,26,12,109,58,247,0
...,...,...,...,...,...,...,...,...,...,...,...
10672,832,Lakshadweep,Lakshadweep,2014,1,0,0,1,2,0,0
10673,833,Lakshadweep,Total District(s),2014,1,0,0,1,2,0,0
10674,834,Puducherry,Karaikal,2014,3,1,0,12,1,1,0
10675,835,Puducherry,Puducherry,2014,7,6,1,20,7,3,0
10676,836,Puducherry,Total District(s),2014,10,7,1,32,8,4,0

In [38]:
def create_holes(dataframe, column_name, hole_percentage = 10):

  if hole_percentage < 0 or hole_percentage > 100:
    raise ValueError("Процент дырявости должен быть в диапазоне от 0 до 100.")

  dataframe_with_holes = dataframe.copy()
  num_holes = int(len(dataframe) * (hole_percentage / 100))
  hole_indices = np.random.choice(len(dataframe), num_holes, replace=False)
  dataframe_with_holes.loc[hole_indices, column_name] = np.nan

  return dataframe_with_holes

df = create_holes(df, 'Kidnapping and Abduction')
df

,Unnamed: 0,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
0,0,ANDHRA PRADESH,ADILABAD,2001,50,30.0,16,149,34,175,0
1,1,ANDHRA PRADESH,ANANTAPUR,2001,23,30.0,7,118,24,154,0
2,2,ANDHRA PRADESH,CHITTOOR,2001,27,34.0,14,112,83,186,0
3,3,ANDHRA PRADESH,CUDDAPAH,2001,20,20.0,17,126,38,57,0
4,4,ANDHRA PRADESH,EAST GODAVARI,2001,23,26.0,12,109,58,247,0
...,...,...,...,...,...,...,...,...,...,...,...
10672,832,Lakshadweep,Lakshadweep,2014,1,0.0,0,1,2,0,0
10673,833,Lakshadweep,Total District(s),2014,1,0.0,0,1,2,0,0
10674,834,Puducherry,Karaikal,2014,3,1.0,0,12,1,1,0
10675,835,Puducherry,Puducherry,2014,7,NaN,1,20,7,3,0
10676,836,Puducherry,Total District(s),2014,10,NaN,1,32,8,4,0

In [39]:
#Удаление
df_cleaned = df.dropna()

df_cleaned

,Unnamed: 0,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
0,0,ANDHRA PRADESH,ADILABAD,2001,50,30.0,16,149,34,175,0
1,1,ANDHRA PRADESH,ANANTAPUR,2001,23,30.0,7,118,24,154,0
2,2,ANDHRA PRADESH,CHITTOOR,2001,27,34.0,14,112,83,186,0
3,3,ANDHRA PRADESH,CUDDAPAH,2001,20,20.0,17,126,38,57,0
4,4,ANDHRA PRADESH,EAST GODAVARI,2001,23,26.0,12,109,58,247,0
...,...,...,...,...,...,...,...,...,...,...,...
10665,825,Delhi UT,South-East,2014,266,402.0,24,469,123,312,0
10670,830,Delhi UT,West,2014,251,546.0,13,484,63,416,0
10672,832,Lakshadweep,Lakshadweep,2014,1,0.0,0,1,2,0,0
10673,833,Lakshadweep,Total District(s),2014,1,0.0,0,1,2,0,0
10674,834,Puducherry,Karaikal,2014,3,1.0,0,12,1,1,0

In [18]:
#Заполнение при помощи медианы

In [ ]:
#Заполнение при помощи среднего

In [ ]:
#Заполнение при помощи моды

In [ ]:
#Заполнение при помощи интерполяции

**Объясните**

##Поиск выбросов и аномалий

**Те, кто выполняет задания со * делают поиск выбросов с помощью написанного ранее класса**

Найти выбросы по числовой переменной (использовать метод основанный на среднем и на межквартильном размахе). Объясните результат

Вывести статистику с выбросами и без. Сравните и объясните результат

In [ ]:
#Методом среднего

In [ ]:
#При помощи межквартильного размаха

In [ ]:
#Статистика и объяснение

**Объяснения**

##Дубликаты

Проверьте датафрейм на дубликаты и удалите их, если дублей нет - создайте.

In [ ]:
#Проверка на дубли

In [ ]:
#Удаление дублей

## Преобразование признаков

Масштабируйте числовые признаки через MinMaxScaler, StandardScaler

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Creating instances
min_max_scaler = MinMaxScaler()
standard_scaler = StandardScaler()

Масштабируйте категориальные признаки через OneHotEncoder

In [ ]:
from sklearn.preprocessing import OneHotEncoder

# Create an instance of OneHotEncoder
encoder = OneHotEncoder()

##Задание для гениев*


Реализовать расчет корреляции Спирмана

In [ ]:
#Функция по расчету тут

In [ ]:
#Пример использования тут и объяснение принципа работы

###Пример реализации

In [ ]:
import pandas as pd
import numpy as np


def corr_pearson(column_1, column_2):
  cov = np.cov(column_1, column_2)
  return cov/(column_1.std() * column_2.std())

In [ ]:
data = {
    'Рост': [170, 155, 180, 162, 175],
    'Вес': [65, 50, 75, 55, 70]
}
df = pd.DataFrame(data)
df

   Рост  Вес
0   170   65
1   155   50
2   180   75
3   162   55
4   175   70

In [ ]:
corr_pearson(df["Рост"], df["Вес"])

array([[0.96593129, 0.99674864],
       [0.99674864, 1.03527033]])